apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: redis-cert
  namespace: databases
spec:
  secretName: redis-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: redis.example.com
  dnsNames:
  - redis.example.com