apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infrastructure
resources:
  - https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.6.4/deploy/static/provider/cloud/deploy.yaml
  - clusterissuer.yaml
  - cert-manager-email.yaml

generatorOptions:
  disableNameSuffixHash: true

vars:
  - name: EMAIL
    objref:
      kind: Secret
      name: cert-manager-email
      namespace: infrastructure
      apiVersion: v1
    fieldref:
      fieldpath: stringData.email