apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cert-manager      # Install cert-manager (creates its own namespace)
  - namespaces       # Create other namespaces
  - ingress
  - databases      
  - messaging
  - monitoring
  - search
  - storage
  