apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces        # Create namespaces first
  - cert-manager      # Install cert-manager
  - ingress
  - databases      
  - messaging
  - monitoring
  - search
  - storage
  